version: "3"
services:
  frontend:
    image: node:18
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: yarn dev
    ports:
      - 3000:5173
  memo-back:
    build: ./backend
    volumes:
      - ./backend/prisma/dev.db:/db/sqlite
      - /tmp/memo:/tmp
