version: "3"
services:
  frontend:
    image: node:18
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: yarn dev
    ports:
      - 3000:5173

  backend:
    image: node:18
    volumes:
      - ./backend:/app
      - ./db:/db
    working_dir: /app
    command: yarn dev
